mysql:
  user: ''
  password: ''
  host: localhost
  database: bukkit
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
  savesPerDay: 64
commonSettings:
  cancelReinforcementModeInBastionField: false
  listBastionTimeout: 2000
  warzoneBroadcastInterval: 1800000
  cancelPlacementAndDamage:
    - SCAFFOLDING
bastions:
#The first bastion in this list will be used as the default type
#This only really matters the first time your start it up when converting from old bastion
#All bastions in the db will be flagged as, in this instance, citybastion
  citybastion:
    block:
      material: NETHER_WART_BLOCK
      durability: 0
      name: City Bastion
      lore: 
        - This bastion will protect your plot
    shortName: City
    squarefield: true
    effectRadius: 50
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: false
    destroyOnRemoveWhileImmature: true
    createWarzone: false
    disableReinforcements: false
    pearls:
      block: false
      blockMidair: fakse
      scaleFactor: 1
      requireMaturity: true
      consumeOnBlock: false
      damageFirstBastion: false
    elytra:
      block: true
      scaleFactor: 1
      requireMaturity: true
      destroyOnBlock: false
      damageOnBlock: true
      explodeOnBlock: true
      explodeOnBlockStrength: 0
  claimbastion:
    block:
      material: BONE_BLOCK
      durability: 0
      name: Claim Bastion
      lore: 
        - This bastion will protect your claims
    squarefield: false
    effectRadius: 300
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: false
    onlyDirectDestroy: true
    destroyOnRemoveWhileImmature: true
    createWarzone: false
    disableReinforcements: false
    pearls:
      block: false
      blockMidair: false
      scaleFactor: 1
      requireMaturity: true
      consumeOnBlock: false
      damageFirstBastion: false
    elytra:
      block: false
      scaleFactor: 1
      requireMaturity: true
      destroyOnBlock: false
      damageOnBlock: true
      explodeOnBlock: true
      explodeOnBlockStrength: 0
  bastion:
    block:
      material: SPONGE
      durability: 0
      name: Bastion
      lore: 
        - this one is hellaz
    squarefield: false
    effectRadius: 10
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: false
    createWarzone: false
    disableReinforcements: false
    pearls:
      block: true
      blockMidair: true
      scaleFactor: 2
      requireMaturity: true
      consumeOnBlock: true
      damageFirstBastion: true
    elytra:
      block: true
      scaleFactor: 1
      requireMaturity: true
      destroyOnBlock: true
      damageOnBlock: false
      explodeOnBlock: true
      explodeOnBlockStrength: 0
  attackbastion:
    block:
      material: EMERALD_BLOCK
      durability: 0
      name: Attack Bastion
      lore:
        - This bastion will is an EMP on a charge. Only placeable in a warzone.
    squarefield: false
    effectRadius: 10
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 600000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: true
    createWarzone: false
    disableReinforcements: true # warzone only
    pearls:
      block: false
      blockMidair: false
      scaleFactor: 2
      requireMaturity: false
      consumeOnBlock: false
      damageFirstBastion: false
    elytra:
      block: false
      scaleFactor: 1
      requireMaturity: false
      destroyOnBlock: false
      damageOnBlock: false
      explodeOnBlock: false
      explodeOnBlockStrength: 0
  warzonebastion:
    block:
      material: DIAMOND_BLOCK
      durability: 0
      name: Attack Bastion
      lore:
        - This bastion will declare a warzone.
    squarefield: false
    effectRadius: 50
    includeY: true
    startScaleFactor: 100
    finalScaleFactor: 0.2
    warmupTime: 86400000
    erosionPerDay: 0
    regenPerDay: 0
    blocksToErode: 1
    placementCooldown: 2000
    destroyOnRemove: true
    onlyDirectDestroy: true
    createWarzone: true
    disableReinforcements: false
    warzone:
      bastion
    pearls:
      block: false
      blockMidair: false
      scaleFactor: 2
      requireMaturity: false
      consumeOnBlock: false
      damageFirstBastion: false
    elytra:
      block: false
      scaleFactor: 1
      requireMaturity: false
      destroyOnBlock: false
      damageOnBlock: false
      explodeOnBlock: false
      explodeOnBlockStrength: 0
